### ISSUE TITLE
🐞 Bug: CI fails to hit this GitHub repository 

### ISSUE THREAD

**Issue by gregmacfarlane** [tfresource/tfresource.github.io#400]
## Current Behavior

On recent pull requests, the CI build has [failed with an error](https://github.com/tfresource/tfresource-website/actions/runs/3879142945/jobs/6616035365#step:5:956) suggesting this website is unavailable.

```
fatal: unable to access 'https://github.com/tfresource/tfresource-website.git/': The requested URL returned error: 403
```

## Desired Behavior

The CI needs to work

- [x] Sufficiently defined  
- [x] Severity labeled

**Comment by gregmacfarlane** [comment]
It seems as though the inability to build cleanly is affecting our loading of pyodide libraries, affecting #405 and testing some of these additional features.

**Comment by gregmacfarlane** [comment]
Might have something to do with GitHub actions, where one is working and one is not. @lmz will keep digging further.

**Comment by lmz** [comment]
I think this is fixed: https://github.com/tfresource/tfresource-website/commit/64dc4cedd25c813b02412f7c11eea6d1e1006f4f
The process succeeded: https://github.com/tfresource/tfresource-website/actions
