### ISSUE TITLE
🐞 Bug: Google Analytics no longer configured

### ISSUE THREAD

**Issue by gregmacfarlane** [tfresource/tfresource.github.io#418]
## Current Behavior

The google analytics setup we have used is no longer working. There is an error bar on the analytics page stating

```This property has stopped processing data. To continue measuring website performance, set up a Google Analytics 4 (GA4) property.```

## Desired Behavior

We need to update the google analytics loggers to make sure the system is modernized

## Issue Ready Checklist

- [ ] Sufficiently defined  
- [ ] Severity labeled

**Comment by billyc** [comment]
@gregmacfarlane  - I modified the code to support the new GA-4. It says it can take "up to 48 hours" -- I'll check back tomorrow to see if data collection has restarted.

Gotta love google deprecating/canceling everything... :-/

**Comment by billyc** [comment]
@gregmacfarlane  it looks like it is active now. Data is flowing.

Safari blocks third party cookies by default and Firefox blocks the entire Analytics script. But Chrome users without ad blockers will still be sending page hit data.

**Comment by gregmacfarlane** [comment]
![Screenshot 2024-01-13 at 3 57 44 PM](https://github.com/tfresource/tfresource-website/assets/2234830/e43e3d66-1e99-4883-ba3f-99bfdc99d1af)
Looks fixed to me!
